_name_: EMP
dataset_name: H4ac_txt
dest_path: null
max_length: 1024
d_output: ${.${.dataset_name}.classes}
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
H3_txt:
  train_len: 13468
  classes: 2
H3K4me1_txt:
  train_len: 28509
  classes: 2
H3K4me2_txt:
  train_len: 27614
  classes: 2
H3K4me3_txt:
  train_len: 33119
  classes: 2
H3K9ac_txt:
  train_len: 25003
  classes: 2
H3K14ac_txt:
  train_len: 29743
  classes: 2
H3K36me3_txt:
  train_len: 31392
  classes: 2
H3K79me3_txt:
  train_len: 25953
  classes: 2

H4_txt:
  train_len: 13140
  classes: 2

H4ac_txt:
  train_len: 30685
  classes: 2