_name_: genomic_structure_dataset_orca
dataset_name: h1esc
dest_path: /data/genomic_structure/resources/resources
max_length: 1024
d_output: ${.${.dataset_name}.classes}
total_size: 100
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
h1esc:
  train_len: 10000
  classes: 6

hff:
  train_len: 10000
  classes: 6

hctnoc:
  train_len: 10000
  classes: 6
  
  