_name_: plant_genomic_benchmark
dataset_name: lncrna/s_lycopersicum
dest_path: null
max_length: 1024
d_output: ${.${.dataset_name}.classes}
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
#max length 398
splicing/arabidopsis_thaliana_donor:
  train_len: 2588034
  classes: 2
splicing/arabidopsis_thaliana_acceptor:
  train_len: 1704844
  classes: 2


poly_a/arabidopsis_thaliana:
  train_len: 170835
  classes: 2
poly_a/chlamydomonas_reinhardtii:
  train_len: 90378
  classes: 2
poly_a/medicago_truncatula:
  train_len: 47277
  classes: 2
poly_a/oryza_sativa_indica_group:
  train_len: 98139
  classes: 2
poly_a/oryza_sativa_japonica_group:
  train_len: 120621
  classes: 2
poly_a/trifolium_pratense:
  train_len: 111138
  classes: 2

lncrna/g_max:
  train_len: 11430
  classes: 2
lncrna/m_esculenta:
  train_len: 4934
  classes: 2
lncrna/s_bicolor:
  train_len: 8654
  classes: 2
lncrna/s_lycopersicum:
  train_len: 7247
  classes: 2
lncrna/t_aestivum:
  train_len: 11252
  classes: 2
lncrna/z_mays:
  train_len: 8423
  classes: 2


# chromatin_access/arabidopsis_thaliana:
#   train_len: 174756
#   classes: 2
# chromatin_access/brachypodium_distachyon:
#   train_len: 174756
#   classes: 2
# chromatin_access/oryza_sativa_MH63_RS2:
#   train_len: 174756
#   classes: 2
# chromatin_access/oruza_sativa_ZS97_RS2:
#   train_len: 174756
#   classes: 2
# chromatin_access/setaria_italica:
#   train_len: 174756
#   classes: 2
# chromatin_access/sorghum_bicolor:
#   train_len: 174756
#   classes: 2
# chromatin_access/zea_mays:
#   train_len: 174756
#   classes: 2
# there are 8 datasets in this suite, choose 1 at a time, with their corresponding settings
# name                                num_seqs        num_classes     median len    std
# dummy_mouse_enhancers_ensembl       1210            2               2381          984.4  
# demo_coding_vs_intergenomic_seqs    100_000         2               200           0
# demo_human_or_worm                  100_000         2               200           0
# human_enhancers_cohn                27791           2               500           0
# human_enhancers_ensembl             154842          2               269           122.6
# human_ensembl_regulatory            289061          3               401           184.3
# human_nontata_promoters             36131           2               251           0
# human_ocr_ensembl                   174756          2               315           108.1
