_name_: prom
dataset_name: prom_core_tata_txt
dest_path: null
max_length: 1024
d_output: ${.${.dataset_name}.classes}
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
prom_300_all_txt:
  train_len: 47356
  classes: 2

prom_300_notata_txt:
  train_len: 42452
  classes: 2

prom_300_tata_txt:
  train_len: 4904
  classes: 2

prom_core_all_txt:
  train_len: 47356
  classes: 2

prom_core_notata_txt:
  train_len: 42452
  classes: 2


prom_core_tata_txt:
  train_len: 4904
  classes: 2