_name_: promoter_prediction
dataset_name: 0_txt
dest_path: null
max_length: 8000
d_output: ${.${.dataset_name}.classes}
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
0_txt:
  train_len: 7288
  classes: 2



