_name_: splicing_prediction
dataset_name: '0'
dest_path: null
max_length: 1024
d_output: ${.${.dataset_name}.classes}
l_output: 5000
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
'0':
  train_len: 1210
  classes: 3

