_name_: tf
dataset_name: 4_txt
dest_path: null
max_length: 1024
d_output: ${.${.dataset_name}.classes}
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
0_txt:
  train_len: 32378
  classes: 2

1_txt:
  train_len: 30672
  classes: 2

2_txt:
  train_len: 19000
  classes: 2

3_txt:
  train_len: 27294
  classes: 2

4_txt:
  train_len: 19000
  classes: 2

