# _target_:
_name_: base
loss: binary_cross_entropy
metrics: 
  - roc_auc_macro
  - accuracy_multilabel
  # - roc_auc_micro
  # - recall_per_class
  - f1_macro
torchmetrics: null
  # - AUROC
  # - Precision
  # - Recall
  # - F1Score
